Repository SzFMV2019-Osz/AutomatedCar-A, pull requests merged in 2019-12, with the labels that each got.

#216 F/202 relevans tablak kigyujtese
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Camera.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Car.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/IObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtil.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/Dashboard.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/Gui.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtilTest.java
Labels: enhancement

#215 #214 - car képbetöltés fix
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Car.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/Consts.java
Labels: bug

#218 F/201 tabla megjelenitese a dashboardon
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Sign.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/Dashboard.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/dashboard/LastRoadSign.java
Labels: enhancement

#224 Team a4
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/AutomatedEmergencyBrake.java
Labels: integration

#223 Team a2
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/Main.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Camera.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Car.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/NPC.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Sign.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/TurningPoint.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/TurningPoints.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/UltraSound.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/UltraSoundSensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/IObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/managers/WorldManager.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/Consts.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtil.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/InputManager.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Powertrain.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/virtualfunctionbus/packets/InputPacket.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/virtualfunctionbus/packets/OutgoingInputPacket.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/virtualfunctionbus/packets/PowertrainPacket.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/CourseDisplay.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/Dashboard.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/DebugViewer.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/Gui.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/dashboard/LastRoadSign.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/debug/DebugViewer.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/interfaces/IDetectedObjects.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/interfaces/IRadarClosestObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/interfaces/ISensorAreaInterface.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/interfaces/ISwitchableDebugViewer.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/XmlParser.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/TurningPointConverter.java
  src/main/resources/car_npc_road_1.xml
  src/main/resources/test_world_1kmx1km.xml
  src/main/resources/walker_npc_road_1.xml
  src/test/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtilTest.java
Labels: integration
