Repository SzFMV2019-Osz/AutomatedCar-A, pull requests merged in 2019-10, with the labels that each got.

#68 F/#57 model messages
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/Main.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Car.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Crosswalk.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingBollard.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingSpace.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Position.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Road.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Sign.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Transform.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Tree.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/World.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/WorldObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/IBackground.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/ICrashable.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/IDynamic.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/IStatic.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/IWorld.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/managers/WorldManager.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/Consts.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtil.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/CourseDisplay.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/XmlParser.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/DoubleConverter.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/IntegerConverter.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/ObjectConverter.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/xml/XmlParserTest.java
Labels: enhancement

#76 #36 All currently important classes for the HMI
  README.md
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ACC.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Control.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/GearShift.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ACCTest.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/ControlTest.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/GearShiftTest.java
Labels: enhancement

#69 #29 #50 WorldManager lekérdezések
  src/main/java/hu/oe/nik/szfmv/automatedcar/Main.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Transform.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/World.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/WorldObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/managers/WorldManager.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/Consts.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtil.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/XmlParser.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/ObjectConverter.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtilTest.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/xml/XmlParserTest.java
Labels: task

#91 F/#51 reference position beolvasas
  pom.xml
  src/main/java/hu/oe/nik/szfmv/automatedcar/Main.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingBollard.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/References.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/World.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/WorldObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/IObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/managers/WorldManager.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/Consts.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtil.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/XmlParser.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/ObjectConverter.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/ReferenceConverter.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/xml/XmlParserTest.java
  src/test/resources/mini_reference.xml
Labels: task

#107 F/force vector
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/IPowertrain.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Powertrain.java
Labels: task

#104 Autó haladási irányának meghatározása a sebességváltó állás alapján
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/IPowertrain.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Powertrain.java
Labels: task

#111 F/moving vector
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/IPowertrain.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Powertrain.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/virtualfunctionbus/packets/PowertrainPacket.java
Labels: task

#119 F/inside gear shift fix
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/IPowertrain.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Powertrain.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/virtualfunctionbus/VirtualFunctionBus.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/virtualfunctionbus/packets/PowertrainPacket.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/virtualfunctionbus/packets/UserInputPacket.java
Labels: task

#124 #hotfix - nem tölti be az automated cart
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtil.java
Labels: bug

#155 Shapek és DebugViewer javítása
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Car.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Crosswalk.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingBollard.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingSpace.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Road.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Sign.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Tree.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/WorldObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/IObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtil.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/CourseDisplay.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/debug/DebugViewer.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/model/ShapeTest.java
Labels: bug

#159 B/master remote tracking
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/HMI.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/InputManager.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/CourseDisplay.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/Dashboard.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/dashboard/ILastRoadSign.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/dashboard/LastRoadSign.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/dashboard/StatusIndicator.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/debug/DebugViewer.java
Labels: integration

#160 Team a2
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Car.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Crosswalk.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingBollard.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingSpace.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Road.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Sign.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Tree.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/WorldObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/IObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtil.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/CourseDisplay.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/debug/DebugViewer.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/model/ShapeTest.java
Labels: integration

#151 World Manager Poligonokkal
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/Main.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Car.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Crosswalk.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingBollard.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingSpace.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/References.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Road.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Sign.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Transform.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Tree.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/World.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/WorldObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/managers/WorldManager.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/Consts.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtil.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/CourseDisplay.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/debug/DebugViewer.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/XmlParser.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/DoubleConverter.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/ObjectConverter.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/ReferenceConverter.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/model/WorldObjectTest.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtilTest.java
Labels: enhancement
