Repository SzFMV2019-Osz/AutomatedCar-A, pull requests merged in 2019-11, with the labels that each got.

#180 F/#166 kamera szenzorok
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Car.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/RoadSensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Sensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/SignSensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/ISensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/managers/WorldManager.java
Labels: task

#190 F/167 savtartas elokeszites kiegeszites
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Camera.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/RoadSensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Sensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/SignSensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/ISensor.java
Labels: enhancement

#185 F/npc small
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/Main.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Car.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Crosswalk.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/NPC.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingBollard.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingSpace.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Road.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Sign.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Tree.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/TurningPoint.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/TurningPoints.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/WorldObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/IObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/managers/WorldManager.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtil.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/systemcomponents/Powertrain.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/virtualfunctionbus/packets/PowertrainPacket.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/CourseDisplay.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/debug/DebugViewer.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/XmlParser.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/TurningPointConverter.java
  src/main/resources/car_npc_road_1.xml
  src/main/resources/walker_npc_road_1.xml
  src/test/java/hu/oe/nik/szfmv/automatedcar/model/ShapeTest.java
Labels: sprint2

#194 Team a2
  src/main/java/hu/oe/nik/szfmv/automatedcar/AutomatedCar.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/Main.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/exceptions/CrashException.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Camera.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Car.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Crosswalk.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingBollard.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/ParkingSpace.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/References.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Road.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/RoadSensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Sensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Sign.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/SignSensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Transform.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/Tree.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/World.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/WorldObject.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/ICrashable.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/interfaces/ISensor.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/managers/WorldManager.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/Consts.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtil.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/CourseDisplay.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/visualization/debug/DebugViewer.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/XmlParser.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/DoubleConverter.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/ObjectConverter.java
  src/main/java/hu/oe/nik/szfmv/automatedcar/xml/converter/ReferenceConverter.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/model/WorldObjectTest.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/model/utility/ModelCommonUtilTest.java
  src/test/java/hu/oe/nik/szfmv/automatedcar/xml/XmlParserTest.java
  src/test/resources/car_1_blue.png
  src/test/resources/car_1_red.png
  src/test/resources/car_1_white.png
  src/test/resources/car_2_blue.png
  src/test/resources/car_3_black.png
  src/test/resources/mini_world.xml
Labels: integration
